In [1]:
from datascience import *
import numpy as np

# Comparisons

In [26]:
1 > 2 

False

In [27]:
make_array(1,2,3,4) > 2

array([False, False,  True,  True])

# Functions

In [1]:
def double(x):
    '''
    Doubles the value of x
    
    x: numeric, number you want to double
    '''
    
    return 2*x

In [2]:
double(2)

4

In [3]:
def area_of_rectangle(s1, s2):
    '''
    Calculates the area of a rectangle
    
    s1,s2: numeric, sides of rectangle
    '''
    
    return s1*s2

In [7]:
counties = Table.read_table('counties.csv')

In [8]:
counties.show(5)

In [13]:
counties.labels

('SUMLEV',
 'REGION',
 'DIVISION',
 'STATE',
 'COUNTY',
 'STNAME',
 'CTYNAME',
 'CENSUS2010POP',
 'ESTIMATESBASE2010',
 'POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'NPOPCHG_2010',
 'NPOPCHG_2011',
 'NPOPCHG_2012',
 'NPOPCHG_2013',
 'NPOPCHG_2014',
 'BIRTHS2010',
 'BIRTHS2011',
 'BIRTHS2012',
 'BIRTHS2013',
 'BIRTHS2014',
 'DEATHS2010',
 'DEATHS2011',
 'DEATHS2012',
 'DEATHS2013',
 'DEATHS2014',
 'NATURALINC2010',
 'NATURALINC2011',
 'NATURALINC2012',
 'NATURALINC2013',
 'NATURALINC2014',
 'INTERNATIONALMIG2010',
 'INTERNATIONALMIG2011',
 'INTERNATIONALMIG2012',
 'INTERNATIONALMIG2013',
 'INTERNATIONALMIG2014',
 'DOMESTICMIG2010',
 'DOMESTICMIG2011',
 'DOMESTICMIG2012',
 'DOMESTICMIG2013',
 'DOMESTICMIG2014',
 'NETMIG2010',
 'NETMIG2011',
 'NETMIG2012',
 'NETMIG2013',
 'NETMIG2014',
 'RESIDUAL2010',
 'RESIDUAL2011',
 'RESIDUAL2012',
 'RESIDUAL2013',
 'RESIDUAL2014',
 'GQESTIMATESBASE2010',
 'GQESTIMATES2010',
 'GQESTIMATES2011',
 '

In [9]:
counties.group('STNAME')

STNAME               | count
Alabama              | 68
Alaska               | 30
Arizona              | 16
Arkansas             | 76
California           | 59
Colorado             | 65
Connecticut          | 9
Delaware             | 4
District of Columbia | 2
Florida              | 68
... (41 rows omitted)

In [11]:
def higher_pop(x, y):
    return max(x,y)

In [12]:
counties.apply(higher_pop,'POPESTIMATE2013', 'POPESTIMATE2014')

array([4849377,   55395,  200111, ...,   21031,    8450,    7201])

#### Question: Which county had the greatest change in population from 2010 to 2011?

In [25]:
counties.apply(abs, 'NPOPCHG_2011')

array([15873,   591,  3478, ...,   186,    75,    67])

#### Question: What was the percent change in estimated population for each county between 2011 and 2012?

#### Question: Which counties had the greatest change in population between 2013 and 2014?

## Finding Percentages

In [8]:
cah = Table.read_table('201709-CAH_PulseOfTheNation.csv')

In [4]:
cah.labels

('Income',
 'Gender',
 'Age',
 'Age Range',
 'Political Affiliation',
 'Do you approve or disapprove of how Donald Trump is handling his job as president?',
 'What is your highest level of education? ',
 'What is your race?',
 'What is your marital status?',
 'What would you say is the likelihood that your current job will be entirely performed by robots or computers within the next decade?',
 'Do you believe that climate change is real and caused by people, real but not caused by people, or not real at all?',
 'How many Transformers movies have you seen? ',
 'Do you agree or disagree with the following statement: scientists are generally honest and are serving the public good. ',
 'Do you agree or disagree with the following statement: vaccines are safe and protect children from disease.',
 'How many books, if any, have you read in the past year?',
 'Do you believe in ghosts?',
 'What percentage of the federal budget would you estimate is spent on scientific research?',
 'Is federal f

In [10]:
cah_new = cah.relabeled('What is your highest level of education? ', 'Education Level').select('Education Level', 'Age Range')

In [12]:
cah_new.show(5)

In [13]:
cah_new.pivot('Education Level', 'Age Range')

Age Range | College degree | Graduate degree | High school | Other | Some college
18-24     | 2              | 0               | 5           | 0     | 2
25-34     | 7              | 2               | 3           | 0     | 3
35-44     | 18             | 13              | 7           | 0     | 3
45-54     | 34             | 30              | 12          | 3     | 25
55-64     | 36             | 20              | 19          | 2     | 23
65+       | 9              | 15              | 8           | 0     | 9

In [14]:
age_educ_table = cah_new.pivot('Education Level', 'Age Range').select('Age Range', 'Graduate degree', 'College degree', 'Some college', 'High school', 'Other')

In [15]:
age_educ_table

Age Range | Graduate degree | College degree | Some college | High school | Other
18-24     | 0               | 2              | 2            | 5           | 0
25-34     | 2               | 7              | 3            | 3           | 0
35-44     | 13              | 18             | 3            | 7           | 0
45-54     | 30              | 34             | 25           | 12          | 3
55-64     | 20              | 36             | 23           | 19          | 2
65+       | 15              | 9              | 9            | 8           | 0

In [16]:
def row_props(a, b, c, d, e):
    overall = a + b + c + d + e
    return make_array(a/overall, b/overall, c/overall, d/overall, e/overall)

In [19]:
age_educ_table.apply(percentages, 'Graduate degree', 'College degree', 'Some college', 'High school', 'Other')

array([[0.        , 0.22222222, 0.22222222, 0.55555556, 0.        ],
       [0.13333333, 0.46666667, 0.2       , 0.2       , 0.        ],
       [0.31707317, 0.43902439, 0.07317073, 0.17073171, 0.        ],
       [0.28846154, 0.32692308, 0.24038462, 0.11538462, 0.02884615],
       [0.2       , 0.36      , 0.23      , 0.19      , 0.02      ],
       [0.36585366, 0.2195122 , 0.2195122 , 0.19512195, 0.        ]])